const cartActionTypes = {
	TOGGLECARTHIDDEN: 'TOGGLECARTHIDDEN',
	Add_ITEM: 'Add_ITEM',
	REMOVE_ITEM: 'REMOVE_ITEM',
	CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
	CLEAR_CART: 'CLEAR_CART',
};

export default cartActionTypes;
